version: '3.2'

services:
    api:
        build:
            context: .
            dockerfile: api/Dockerfile
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
